services:
    SolidInvoice\MoneyBundle\Formatter\MoneyFormatter:
        arguments:
            $locale: '%locale%'
        autowire: true
        lazy: true

    currency:
        class: Money\Currency
        factory: ['@currency_factory', 'getCurrency']

    Money\Currency:
        alias: currency

    currency_factory:
        class: SolidInvoice\MoneyBundle\Factory\CurrencyFactory
        arguments:
            $installed: '%installed%'
        autowire: true
        lazy: true