swiftmailer:
    transport: '%env(mailer_transport)%'
    host: '%env(mailer_host)%'
    username: '%env(mailer_user)%'
    password: '%env(mailer_password)%'
    encryption: '%env(mailer_encryption)%'
    port: '%env(mailer_port)%'
    spool: { type: 'memory' }
