language: php

php:
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true

env:
  global:
    - SYMFONY_ENV=test
    - secure: "nYVUOMZOXXo3dh3ZS2ftNH4U4phz2AMnhGWpwL9FLSGAGiRNF1duP80w2dBb/pJkyLLZXIWI2AL6MDA1CudDKLR2p4hMSi8d1chpTZaBl8R9+R8u/mXilXLRld9PjwYfMcBJxegUzmsggxtwTPtReW1U8sYRsI4ktnXGq1ZuQjXg647ytvYLXbeGo8vqaW4MDXHdoHkmQqnvKl/YbARnT8m6BEahPD1owAWx0NA6O/6Kyoc2nU72GVdSEj6Anrb7WYKPWQvidmj9rUL1Nu3qwRhwsLhRLc+OsiGyOPJLYXMCWEYsyGco4Nn3yKWOnkNUcToUXmTvhcIL7N7mkrqRV7B7iObnjuqYLrxeBL8YYUiVD3SB9r/pwPWIj8/nmopFBNJQqMIeUVMoe+iK1zqx5tdCseMupCMTBIDLc/TdIt0iR38VSRdsJ7YJcLeBQ0y2+XL5Q4mHkZPSuPQQRsRmzQJw/cyfRGyMG/ZGV3bYVq4MfYuvrzRkBAgfxXRg4nCEGEHu4mpJaHqhHAIcpezF8MkcDStFHqJrJCGPwLfw0tbK8BE7eKAulQprIV6RZmbh92nPAdaCBloTt7c2wDpQS7hvyEi4xCv/aD/Jm+M/ipVpPLgL/kXQGv2fKBusocW5yWCV4OAe5nC0zqwiz6pl84MH+4DGawC8fZTRaax81hE="
    - secure: "oWJhFdiagOe1JF30MWJnNQ5J8W2YWAd26iO2BsD0Wl4HcpmyjRH6bTeFqIeNLSMkCQ8OkpteQOVzkkAzpN4TCCVJJJdQxsmikLQztHziqz9gQeHWMPpLQiMWXr+0XxAnJTGEeqaQsBi9DS+DAJsusVl4IbRop4ZSdAuJrPmvnrbe3+HLJ6hG7fQeuNzxvypFCeV4zR4shs9tFB4KY9FJLgpksm2CQ2G4GYSB/S1CJzQlbbKMYugI8wT4d5P5tGyKJB/HIeg8gv/32QY9WuWlFiLfMjLxP3wKm7UMMM4W68MTHYK0bSD5xiu58Tkx0HHPQSsYjqKf79cfAJv0dX533Ed+77kUjFdHaoqWphfwym7YYdZp5um7LYUN1HwWLxw3xJeBWUVQJMqKVtmCHewGKfeg8Pc0NuqmqNUNVPh4YmWKmqT3Qtw8ZDR7sAHhfF6QQrHDse/jScR1itwGTB7LcLfHB5P12tgXedRyEvYLQ9mB4VAj6MtPNq56YcGHtdSiR0eaASJm47d5G9D9erf8cVyibhdMqM14wDHmD2r2kkk5EYS/FxWECAa/qbXqhBAbxYpFqjtDoe3R76mZlhYHQfYWhbYY5SKi7DtpgEklpubXCdEUbWuO0zBK6wuQo02G7PowxOpVvO4zjc8QISkLVnzN3ukRjETUa8pwt8crVms="

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install --prefer-source -n
  - npm install
  - sed -i 's/base_url:\ null/base_url:\ http:\/\/localhost/g' app/config/parameters.yml
  - php app/console cache:clear
  - php app/console assets:install -n

before_script:
  - npm install -g gulp
  - mysql -e 'create database csbill;'
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm"* ]]; then echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - php app/check.php
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - bash travis/travis-ci-apache.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - if [[ "$SAUCE_USERNAME" ]]; then bash travis/sauce.sh; fi;
  - gulp

script:
  - composer validate
  - php app/console security:check
  - bash travis/behat.sh
  - bash travis/phpunit.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - travis_retry php ./bin/coveralls -v

notifications:
  webhooks:
    - http://savage.csbill.org/savage/travis
  hipchat:
    rooms:
      secure: Wc5cg/o//7DW9G0mosA5wmmECr9+R7S/FmVFvZU2mBBpfaE5nY873hePRrMK/Dhiu2aD5R/ll6d7b3mT7oiWzO/rMgQ+U/DcMmgqHYiYrtEz4umi+1EuSLURDAxyv3rDiXHhEWwbYcHfE1Tcfs07Aj4JWSZheploBRpg3iqzMbw=
