language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

sudo: false

env:
  global:
    - secure: "RseUypq34oKYkpon4UJCaN+0YrAfUPg78xS6NSu0RElW949MviD+2VGfVIoelQTwoQAd/ggICPZSMSGXY+NOwBKxvaYmAberAEoNb0DzXW6KPXAmpvfdjFJ5t2TCU1pGLyjg059jsJI/UdEJa/9EGFWNS0ZVyebNIgv3yl1J7cY="
    - secure: "Ri6tvMLROKS/zbvkU8JL9tqUomjYXoSbW3GQRNfAHSwo83pCB2USj0AAiqq9xDma0ecRH4rES9aWrdJmD7wTES0E818dRqMwnDbe5N87/9JrkUp8AC3T8xnSdnz5fffZu4pTkNiwV8XQ5XktXGQ68Qh4Ru+5O5iEXHcSWant8cs="
    - SAUCE_USERNAME=pierredup
    - SAUCE_ACCESS_KEY=37de17cb-dfbe-4519-804c-01b24bc88c31

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  sauce_connect: true

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'create database csbill;'
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm"* ]]; then echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - php app/check.php
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - echo $SAUCE_USERNAME

script:
  - php app/console security:check
  - ./bin/behat --suite=installation -n -f progress -vvv
  - ./bin/phpunit -c app

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6"* ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6"* ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;
  - php ./bin/coveralls -v

notifications:
  webhooks:
    - http://savage.csbill.org/savage/travis
  hipchat:
    rooms:
      secure: Wc5cg/o//7DW9G0mosA5wmmECr9+R7S/FmVFvZU2mBBpfaE5nY873hePRrMK/Dhiu2aD5R/ll6d7b3mT7oiWzO/rMgQ+U/DcMmgqHYiYrtEz4umi+1EuSLURDAxyv3rDiXHhEWwbYcHfE1Tcfs07Aj4JWSZheploBRpg3iqzMbw=
