config:
    shim:
        backgrid:
            deps:
                - backbone
                - lodash
            exports: Backgrid
        grid/backgrid-filter:
            deps:
                - backgrid
        grid/backgrid-paginator:
            deps:
                - backgrid
        grid/backgrid-select-all:
            deps:
                - backgrid
    paths:
        backgrid: ../assets/backgrid.js
        grid/backgrid-filter: ../assets/backgrid-filter.js
        grid/backgrid-paginator: ../assets/backgrid-paginator.js
        grid/backgrid-select-all: ../assets/backgrid-select-all.js
        grid: solidinvoicedatagrid/js/
