#
# This file is part of the CSBillSettingsBundle package.
#
# (c) Pierre du Plessis <info@customscripts.co.za>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

_settings:
    pattern:  /settings
    defaults: { _controller: CSBillSettingsBundle:Settings:index }
