services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            autowire: true
            public: false
            tags:
                - { name: kernel.event_subscriber }

    SolidInvoice\CoreBundle\Listener\:
        resource: '../../../Listener'

    SolidInvoice\CoreBundle\Listener\SessionRequestListener:
        arguments:
            $secret: '%env(secret)%'

    SolidInvoice\CoreBundle\Listener\TemplateListener: ~

    SolidInvoice\CoreBundle\Doctrine\Listener\CompanyListener:
        tags: ['doctrine.event_subscriber']

    SolidInvoice\CoreBundle\Doctrine\Listener\IdGeneratorListener:
        tags: ['doctrine.event_subscriber']

    SolidInvoice\CoreBundle\Listener\Doctrine\CompanyCreateListener:
        tags: ['doctrine.event_subscriber']
