services:
    solidinvoice.core.config_writer:
        class: SolidInvoice\CoreBundle\ConfigWriter
        arguments: ['@kernel', '@filesystem']

    solidinvoice_core.form.help.extension:
        class: SolidInvoice\CoreBundle\Form\Extension\FormHelpExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    billing.mailer:
        class: SolidInvoice\CoreBundle\Mailer\Mailer
        arguments: ['@mailer', '@settings']
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]
            - [setTemplating, ['@templating']]
            - [setSecurity, ['@security.token_storage']]

    solidinvoice_core.swiftmailer.plugin.cssinline:
        class: SolidInvoice\CoreBundle\Swiftmailer\Plugin\CssInlinerPlugin
        arguments: ['@solidinvoice_core.cssinline']
        tags:
            - { name: swiftmailer.default.plugin }

    solidinvoice_core.cssinline:
        class: TijsVerkoyen\CssToInlineStyles\CssToInlineStyles
        public: false

    oro.cache.abstract:
        class: Doctrine\Common\Cache\FilesystemCache
        arguments: ['%kernel.cache_dir%/requirejs']

    solidinvoice_menu.top:
        class: SolidInvoice\CoreBundle\Menu\Builder
        tags:
            - { name: cs_core.menu, menu: top_right, method: systemMenu, priority: 255 }
            - { name: cs_core.menu, menu: top_right, method: userMenu, priority: 255 }

    solidinvoice_core.field.renderer:
        class: SolidInvoice\CoreBundle\Form\FieldRenderer
        arguments: ['@twig']
        lazy: true

    SolidInvoice\CoreBundle\Routing\Loader\AbstractDirectoryLoader:
        public: false
        lazy: true
        autowire: true
        abstract: true
        arguments:
            $locator: '@file_locator'
            $kernel: '@kernel'

    Symfony\Bridge\Doctrine\RegistryInterface:
        alias: doctrine

    Symfony\Component\HttpFoundation\Session\Session:
        alias: session

    Mpociot\VatCalculator\VatCalculator: ~
    SolidInvoice\CoreBundle\Billing\TotalCalculator:
        autowire: true