services:
    _defaults:
        public: false
        autowire: true
        tags:
            - { name: twig.extension }

    SolidInvoice\CoreBundle\Twig\Extension\GlobalExtension:
        calls:
            - [ setContainer, [ '@service_container' ] ]

    SolidInvoice\CoreBundle\Twig\Extension\BillingExtension:
        arguments: ['@solidinvoice_core.field.renderer']

    SolidInvoice\CoreBundle\Twig\Extension\FileExtension: ~

    SolidInvoice\CoreBundle\Twig\Extension\StatusExtension: ~
    SolidInvoice\CoreBundle\Twig\Extension\SerializerExtension: ~
    Twig_Extensions_Extension_Text:
        class: Twig_Extensions_Extension_Text
