services:

    api_token_authenticator:
        class:     CSBill\ApiBundle\Security\ApiTokenAuthenticator
        arguments: [@api_token_user_provider, @serializer]

    api_token_user_provider:
        class: CSBill\ApiBundle\Security\Provider\ApiTokenUserProvider
        arguments: [@doctrine.orm.entity_manager]