_clients_index:
    pattern:   /
    defaults:  { _controller: CSBillClientBundle:Default:index }

_clients_add:
    pattern:   /add
    defaults:  { _controller: CSBillClientBundle:Default:add }

_clients_edit:
    pattern:   /edit/{id}
    defaults:  { _controller: CSBillClientBundle:Default:edit }

_clients_view:
    pattern:   /view/{id}
    defaults:  { _controller: CSBillClientBundle:Default:view }

_clients_info:
    pattern:   /ajax/info/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:info }
    options:
        expose: true

_clients_add_contact:
    pattern:   /ajax/contacts/add/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:addcontact }

_clients_edit_contact:
    pattern:   /ajax/contacts/edit/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:editcontact }

_clients_contact_card:
    pattern:   /ajax/contacts/card/{id}
    defaults:  { _controller: CSBillClientBundle:Ajax:contactcard }
    options:
        expose: true

    options:
        expose: true