solidinvoice_api:
    resource: '@SolidInvoiceApiBundle/Resources/config/routing.yml'
    prefix: /api

solidinvoice_dashboard:
    resource: '@SolidInvoiceDashboardBundle/Resources/config/routing.yml'

solidinvoice_settings:
    resource: '@SolidInvoiceSettingsBundle/Resources/config/routing.yml'
    prefix: /

solidinvoice_core:
    resource: '@SolidInvoiceCoreBundle/Resources/config/routing.yml'
    prefix: /

solidinvoice_install:
    resource: '@SolidInvoiceInstallBundle/Resources/config/routing.yml'
    prefix: /

solidinvoice_client:
    prefix: /clients
    resource: '@SolidInvoiceClientBundle/Resources/config/routing.yml'

solidinvoice_quote:
    prefix: /quotes
    resource: '@SolidInvoiceQuoteBundle/Resources/config/routing.yml'

solidinvoice_invoice:
    prefix: /invoices
    resource: '@SolidInvoiceInvoiceBundle/Resources/config/routing.yml'

solidinvoice_payment:
    resource: '@SolidInvoicePaymentBundle/Resources/config/routing.yml'
    prefix: /payments

solidinvoice_tax:
    resource: '@SolidInvoiceTaxBundle/Resources/config/routing.yml'
    prefix: /tax

solidinvoice_user:
    resource: '@SolidInvoiceUserBundle/Resources/config/routing.yml'
    prefix: /profile

solidinvoice_datagrid:
    resource: '@SolidInvoiceDataGridBundle/Resources/config/routing.yml'
    prefix: /grid

fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

fos_user_security:
    resource: '@FOSUserBundle/Resources/config/routing/security.xml'

fos_user_profile:
    resource: '@FOSUserBundle/Resources/config/routing/profile.xml'
    prefix: /profile

fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting

fos_user_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'
    prefix: /profile

payum_capture:
    resource: '@PayumBundle/Resources/config/routing/capture.xml'

payum_authorize:
    resource: '@PayumBundle/Resources/config/routing/authorize.xml'

payum_notify:
    resource: '@PayumBundle/Resources/config/routing/notify.xml'

bazinga_jstranslation:
    resource: '@BazingaJsTranslationBundle/Resources/config/routing/routing.yml'
