cs_bill_api:
    resource: "@CSBillApiBundle/Resources/config/routing.yml"
    prefix:   /api

cs_bill_dashboard:
    resource: "@CSBillDashboardBundle/Resources/config/routing.yml"

csbill_settings:
    resource: "@CSBillSettingsBundle/Resources/config/routing.yml"
    prefix:   /

csbill_core:
    resource: "@CSBillCoreBundle/Resources/config/routing.yml"
    prefix:   /

csbill_install:
    resource: "@CSBillInstallBundle/Resources/config/routing.yml"
    prefix:   /

csbill_client:
    prefix:   /clients
    resource: "@CSBillClientBundle/Resources/config/routing.yml"

csbill_quote:
    prefix: /quotes
    resource: "@CSBillQuoteBundle/Resources/config/routing.yml"

csbill_invoice:
    prefix: /invoices
    resource: "@CSBillInvoiceBundle/Resources/config/routing.yml"

csbill_item:
    resource: "@CSBillItemBundle/Resources/config/routing.yml"
    prefix:   /items

csbill_payment:
    resource: "@CSBillPaymentBundle/Resources/config/routing.yml"
    prefix:   /payments

csbill_tax:
    resource: "@CSBillTaxBundle/Resources/config/routing.yml"
    prefix:   /tax

csbill_user:
    resource: "@CSBillUserBundle/Resources/config/routing.yml"
    prefix:   /profile

csbill_datagrid:
    resource: "@CSBillDataGridBundle/Resources/config/routing.yml"
    prefix:   /grid

# External Routes

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"