jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost:      10

    role_hierarchy:
        ROLE_ADMIN:       ~
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_CLIENT:      ROLE_USER
        ROLE_USER: ~

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        api_token_user_provider:
            id: api_token_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern:  ^/api/docs
            anonymous: ~

        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                require_previous_session: false
                success_handler: api.success
                failure_handler: api.failure

        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: api_token_authenticator
            provider: api_token_user_provider

        installer:
            pattern:  ^/install(.*)
            anonymous: ~

        external:
            pattern:  ^/view/(quote|invoice)/([a-zA-Z0-9-]{36})
            anonymous: true
            context: frontend

         # Payments
        create:
            pattern:  ^/payments/create/([a-zA-Z0-9-]{36})
            anonymous: true
            context: frontend

        capture:
            pattern:  ^/payment/(capture|notify|done)/(.*)
            anonymous: true
            context: frontend

        done:
            pattern:  ^/payments/done$
            anonymous: true
            context: frontend

        # Login
        login:
            pattern:  ^/login$
            anonymous: ~

        password_reset:
            pattern:  ^/resetting(.*)
            anonymous: ~

        # Main
        main:
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            pattern:    ^/
            context: frontend
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: "^/view/(quote|invoice)/([a-zA-Z0-9-]{36})$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/install(.*), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # payments
        - { path: "^/payments/create/([a-zA-Z0-9-]{36})$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/payment/capture/(.*), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/payments/done$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
