api_keys:
    pattern: /api
    defaults: { _controller: CSBillUserBundle:Api:index }

api_key_create:
    pattern: /api/create
    defaults: { _controller: CSBillUserBundle:Api:saveToken }

api_key_revoke:
    pattern: /api/revoke/{id}
    defaults: { _controller: CSBillUserBundle:Api:revokeToken }
    methods: [POST]
    options:
        expose: true