imports:
    - { resource: twig.yml }

parameters:
    csbill_core.menu.renderer.class: CSBill\CoreBundle\Menu\Renderer
    csbill_core.menu.provider.class: CSBill\CoreBundle\Menu\Provider
    csbill_core.menu_storage.class: CSBill\CoreBundle\Menu\Storage\MenuStorage
    csbill_core.menu.factory.class: CSBill\CoreBundle\Menu\Factory
    csbill_core.menu.top.class: CSBill\CoreBundle\Menu\Main
    csbill_core.currrency.class: CSBill\CoreBundle\Util\Currency
    csbill_core.doctrine.type.money.class: CSBill\CoreBundle\Doctrine\Type\Money
    csbill_core.form.help.extension.class: CSBill\CoreBundle\Form\Extension\FormHelpExtension
    csbill_core.billing.mailer.class: CSBill\CoreBundle\Mailer\Mailer
    csbill_core.form.type.image_upload.class: CSBill\CoreBundle\Form\Type\ImageUpload
    csbill_core.security.encryption.class: CSBill\CoreBundle\Security\Encryption
    csbill_core.session.request.listener.class: CSBill\CoreBundle\Listener\SessionRequestListener
    csbill_core.settings.loader.class: CSBill\CoreBundle\Settings\SettingsLoader

services:
    csbill_core.menu.factory:
        class: %csbill_core.menu.factory.class%
        arguments: [@router]

    csbill_core.menu.renderer:
        class: %csbill_core.menu.renderer.class%
        arguments: [@service_container, @csbill_core.menu.factory]

    csbill_core.menu.provider:
        class: %csbill_core.menu.provider.class%
        arguments: [@csbill_core.menu.storage]

    csbill_core.menu.storage:
        class: %csbill_core.menu_storage.class%

    csbill_core.menu.top:
        class: %csbill_core.menu.top.class%
        tags:
            - { name: cs_core.menu, menu: top_right, method: topMenu }

    csbill_core.currency:
        class: %csbill_core.currrency.class%
        arguments: [%locale%, %currency%]

    currency:
        alias: csbill_core.currency

    csbill_core.form.help.extension:
        class: %csbill_core.form.help.extension.class%
        tags:
            - { name: form.type_extension, alias: form}

    billing.mailer:
        class: %csbill_core.billing.mailer.class%
        arguments: [@mailer, @settings]
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplating, [@templating]]
            - [setSecurity, [@security.context]]

    csbill_core.form.type.image_upload:
        class: %csbill_core.form.type.image_upload.class%
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: form.type, alias: image_upload }

    csbill_core.security.encryption:
        class: %csbill_core.security.encryption.class%
        arguments: [%kernel.secret%]

    security.encryption:
        alias: csbill_core.security.encryption

    csbill_core.session.request.listener:
        class: %csbill_core.session.request.listener.class%
        arguments: [@session, @security.encryption]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    csbill_core.settings.loader:
            class: %csbill_core.settings.loader.class%
            arguments: [@kernel]
            tags:
                - { name: settings.loader }
