services:
    CSBill\ApiBundle\Serializer\Normalizer\:
        resource: '../../../Serializer/Normalizer/'
        autowire: true
        public: false
        lazy: true
        tags:
            - { name: 'serializer.normalizer', priority: 64 }
        arguments:
            $normalizer: '@api_platform.serializer.normalizer.item'