parameters:
    sylius.controller.process.class: CSBill\InstallBundle\Controller\ProcessController

services:
    installer.controller.process:
        parent: sylius.controller.process
        calls:
            - [setContainer, [@service_container]]

    installation.scenario.flow:
        class: CSBill\InstallBundle\Process\InstallScenario
        calls:
            - [setContainer, [@service_container]]
        tags:
             - { name: sylius.process.scenario, alias: install }

    csbill.installer.check:
        class: CSBill\InstallBundle\Listener\RequestListener
        arguments: [%installed%, @router, %kernel.debug%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }

    csbill.installer.database.migration:
        class: CSBill\InstallBundle\Installer\Database\Migration
        arguments: [@filesystem]
        calls:
            - [setContainer, [@service_container]]

    csbill.installer.database.fixtures:
        class: CSBill\InstallBundle\Installer\Database\FixtureLoader
        calls:
            - [setContainer, [@service_container]]
