services:
    _defaults:
        tags: ['form.handler']

    _instanceof:
        SolidWorx\FormHandler\FormHandlerInterface:
            autowire: true
            public: false

    CSBill\SettingsBundle\Form\Handler\:
        resource: '../../../Form/Handler'
        lazy: true
