datagrid:
    tax_grid:
        source:
            repository: 'SolidInvoiceTaxBundle:Tax'
            method: getGridQuery
        columns:
            id:
                name: id
                label: ID
                editable: false
                cell: integer
            name:
                name: name
                label: Name
                editable: false
                cell: string
            rate:
                name: rate
                label: Rate
                editable: false
                cell: percent
            type:
                name: type
                label: Type
                editable: false
                cell: string
            created:
                name: created
                label: Created
                editable: false
                cell: date
        search:
            fields:
                - rate
                - name
                - type
        line_actions:
            edit:
                icon: edit
                label: tax.grid.actions.edit
                route: _tax_rates_edit
                route_params:
                    id: id
        actions:
            delete:
                label: Delete
                icon: ban
                confirm: 'Are you sure you want to delete the selected rows?'
                action: tax_grid_delete
                className: danger
