services:
    csbill.notification.settings.loader:
        class: CSBill\NotificationBundle\Settings\Loader
        arguments: [@doctrine]
        tags:
            - { name: settings.loader }

    notification.settings.form:
        class: CSBill\NotificationBundle\Form\Type\NotificationType
        tags:
            - { name: form.type, alias: notification }

    notification.sender:
        class: Namshi\Notificator\Manager
        arguments: [[], @logger]

    notification.handler.chained:
        class: CSBill\NotificationBundle\Notification\Handler\ChainedHandler
        arguments: [@notification.sender]
        tags:
            - { name: notification.handler }

    notification.handler.twilio:
        class: CSBill\NotificationBundle\Notification\Handler\TwilioHandler
        arguments:
            - @twilio.client
            - @=service('settings').get('sms.twilio.number')
        tags:
            - { name: notification.handler }

    notification.handler.swiftmailer:
        class: Namshi\Notificator\Notification\Handler\SwiftMailer
        arguments: [@mailer]
        tags:
            - { name: notification.handler }

    notification.handler.hipchat:
        class: Namshi\Notificator\Notification\Handler\HipChat
        arguments: [@hipchat.client]
        tags:
            - { name: notification.handler }

    notification.manager:
        class: CSBill\NotificationBundle\Notification\NotificationManager
        arguments: [@notification.factory, @settings, @notification.sender]

    notification.factory:
        class: CSBill\NotificationBundle\Notification\Factory
        arguments: [@templating, @translator, @settings]

    hipchat.client:
        class: HipChat\HipChat
        arguments:
            - @=service('settings').get('hipchat.auth_token')
            - @=service('settings').get('hipchat.server_url')

    twilio.client:
        class: Services_Twilio
        arguments:
            - @=service('settings').get('sms.twilio.sid')
            - @=service('settings').get('sms.twilio.token')