parameters:
    grid.class: CSBill\DataGridBundle\Grid

services:
    grid.column.extension.status_extension:
        class: CSBill\DataGridBundle\Column\StatusColumn
        arguments: [@twig]
        tags:
            - { name: grid.column.extension }

    grid.column.extension.currency_extension:
        class: CSBill\DataGridBundle\Column\CurrencyColumn
        arguments: [%currency%]
        tags:
            - { name: grid.column.extension }

    grid.column.extension.percent_extension:
        class: CSBill\DataGridBundle\Column\PercentColumn
        tags:
            - { name: grid.column.extension }

    grid.column.extension.client_extension:
            class: CSBill\DataGridBundle\Column\ClientColumn
            arguments: [@twig]
            tags:
                - { name: grid.column.extension }
