services:
    grid.twig.extension:
        class: CSBill\DataGridBundle\Twig\Extension\GridExtension
        arguments: [@grid.repository, @serializer]
        tags:
            - { name: twig.extension }

    grid.repository:
        class: CSBill\DataGridBundle\Repository\GridRepository